apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: akka-handover
  name: akka-handover
spec:
  replicas: 3
  selector:
    matchLabels:
      app: akka-handover
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: akka-handover
        actorSystemName: akka-handover
    spec:
      containers:
        - name: akka-handover
          image: "localhost:32000/akka-handover:1.0.8"
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /alive
              port: management
          readinessProbe:
            httpGet:
              path: /ready
              port: management
          ports:
            # akka remoting
            - name: remoting
              containerPort: 2552
              protocol: TCP
            - name: api
              containerPort: 8000
              protocol: TCP
            # akka-management bootstrap\
            - name: management
              containerPort: 8558
              protocol: TCP
              # when contact-point-discovery.port-name is set for cluster bootstrap,
              # the management port must be named accordingly:
              # name: management
          env:
            # The Kubernetes API discovery will use this service name to look for
            # nodes with this value in the 'app' label.
            # This can be customized with the 'pod-label-selector' setting.
            - name: AKKA_CLUSTER_BOOTSTRAP_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: "metadata.labels['app']"
      terminationGracePeriodSeconds: 90